from __future__ import annotations

from pathlib import Path

from framework.discovery.models import DiscoveredElement, DiscoveredPage, DiscoveredTable

_GENERATED_HEADER = """# GENERATED BY THE APPLICATION DISCOVERY ENGINE — REVIEW BEFORE USE.
#
# Every locator/column below came from real, observed evidence (a live DOM
# element or a reflected database column) — nothing here is guessed. Still:
# read it, verify it against the real application, and move whatever's
# correct into framework/pages or framework/database/models yourself once
# you're satisfied. Do not import directly from a generated/ directory in
# real tests — this file is a draft, not a framework artifact.

"""


class PageObjectGenerator:
    """Renders a Page Object skeleton from a `DiscoveredPage` — one
    locator constant + one stub business-action method per confirmed
    element, following this framework's existing `BasePage` convention
    (locators as class constants, business actions only). Every element
    the discovery engine emitted already passed its own "only stable
    locators" filter, so this generator adds no new guessing — it only
    turns confirmed evidence into a Page Object shape a human can review
    and finish.
    """

    @staticmethod
    def generate(page: DiscoveredPage, *, class_name: str) -> str:
        lines = [_GENERATED_HEADER]
        lines.append("from __future__ import annotations\n")
        lines.append("from framework.pages.base_page import BasePage\n\n")
        lines.append(f"class {class_name}(BasePage):")
        lines.append(f'    """Discovered from {page.url!r} — {len(page.elements)} elements found.')
        lines.append('    """\n')
        lines.append(f"    path = {page.url!r}\n")

        names = [
            PageObjectGenerator._names(element, index)
            for index, element in enumerate(page.elements)
        ]

        for constant_name, _method_name, element in names:
            lines.append(f"    {constant_name} = {PageObjectGenerator._locator_literal(element)}")
        if names:
            lines.append("")

        for constant_name, method_name, element in names:
            lines.append(f"    def {method_name}(self) -> None:")
            if element.element_type in ("input", "textbox"):
                lines.append(
                    f"        raise NotImplementedError("
                    f'"fill_locator with a real test value once confirmed — {constant_name}")'
                )
            else:
                lines.append(
                    f"        self.click_locator(self.locator(self.{constant_name}), "
                    f"description={method_name!r})"
                )
            lines.append("")

        return "\n".join(lines)

    @staticmethod
    def _names(element: DiscoveredElement, index: int) -> tuple[str, str, DiscoveredElement]:
        base = element.locator.accessible_name or element.text or element.element_type or "element"
        slug = (
            "".join(char if char.isalnum() else "_" for char in base)[:40].strip("_") or "element"
        )
        constant_name = f"{slug.upper()}_{index}"
        prefix = "fill" if element.element_type in ("input", "textbox") else "click"
        method_name = f"{prefix}_{slug.lower()}_{index}"
        return constant_name, method_name, element

    @staticmethod
    def _locator_literal(element: DiscoveredElement) -> str:
        locator = element.locator
        if locator.strategy == "role":
            return f"{locator.value!r}  # role={locator.role!r} name={locator.accessible_name!r}"
        if locator.strategy == "test_id":
            return f"{locator.value!r}  # via Locators.test_id()"
        if locator.strategy == "label":
            return f"{locator.value!r}  # via Locators.label()"
        return f"{locator.value!r}"


class DomainModelGenerator:
    """Renders a frozen dataclass skeleton from a `DiscoveredTable`,
    matching the shape `framework/database/models/*.py` already uses.
    """

    _TYPE_KEYWORDS: tuple[tuple[str, str], ...] = (
        ("BOOL", "bool"),
        ("INT", "int"),
        ("SERIAL", "int"),
        ("FLOAT", "float"),
        ("DOUBLE", "float"),
        ("DECIMAL", "float"),
        ("NUMERIC", "float"),
        ("REAL", "float"),
    )

    @staticmethod
    def generate(table: DiscoveredTable, *, class_name: str) -> str:
        lines = [_GENERATED_HEADER]
        lines.append("from __future__ import annotations\n")
        lines.append("from dataclasses import dataclass\n\n")
        lines.append("@dataclass(frozen=True, slots=True)")
        lines.append(f"class {class_name}:")
        lines.append(f'    """Reflected from table `{table.name}`."""\n')
        if not table.columns:
            lines.append("    pass")
        for column in table.columns:
            py_type = DomainModelGenerator._python_type(column.type)
            optional = " | None" if column.nullable and not column.primary_key else ""
            lines.append(f"    {column.name}: {py_type}{optional}")
        return "\n".join(lines)

    @staticmethod
    def _python_type(sql_type: str) -> str:
        upper = sql_type.upper()
        for keyword, py_type in DomainModelGenerator._TYPE_KEYWORDS:
            if keyword in upper:
                return py_type
        return "str"


def write_generated_file(content: str, output_dir: str | Path, filename: str) -> Path:
    """Writes generated code under `output_dir` (created if needed) — the
    convention is a top-level `generated/` directory, gitignored by
    default, so a review pass is always required before anything in it
    reaches a real commit.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    target = output_path / filename
    target.write_text(content, encoding="utf-8")
    return target
