class Timeouts:
    """Default timeouts in milliseconds unless noted otherwise."""

    DEFAULT_ACTION_TIMEOUT_MS = 15_000
    DEFAULT_NAVIGATION_TIMEOUT_MS = 30_000
    SHORT_WAIT_MS = 5_000
    LONG_WAIT_MS = 60_000

    API_REQUEST_TIMEOUT_SECONDS = 30
    DB_QUERY_TIMEOUT_SECONDS = 30
    DB_POOL_TIMEOUT_SECONDS = 10

    RETRY_MAX_ATTEMPTS = 3
    RETRY_WAIT_MULTIPLIER_SECONDS = 1
    RETRY_WAIT_MAX_SECONDS = 10
