from framework.sync.ai_recommendations import MappingRecommendation, recommend_mappings
from framework.sync.analyzer import RepositoryAnalyzer
from framework.sync.capability_catalog import build_capability_catalog
from framework.sync.compatibility import compute_compatibility_report
from framework.sync.cross_language_mapping import lookup_cross_language_mappings
from framework.sync.detectors import (
    DEFAULT_ADAPTERS,
    CypressAdapter,
    FrameworkAdapter,
    JUnitAdapter,
    NUnitAdapter,
    PlaywrightAdapter,
    PytestAdapter,
    RobotBrowserLibraryAdapter,
    RobotFrameworkAdapter,
    RobotRequestsLibraryAdapter,
    RobotSeleniumLibraryAdapter,
    SeleniumAdapter,
    TestNGAdapter,
    WebdriverIOAdapter,
    XUnitAdapter,
)
from framework.sync.diff import diff_analyses
from framework.sync.execution_model import detect_execution_model, detect_reporting_tools
from framework.sync.migration_candidates import select_migration_candidates
from framework.sync.models import (
    AnalysisDiff,
    AutomationInventory,
    CapabilityCatalog,
    CapabilityCategory,
    CompatibilityReport,
    CrossLanguageMapping,
    DetectedFramework,
    ExecutionModel,
    ExistingCapability,
    Finding,
    MappingStatus,
    MigrationCandidate,
    MigrationScope,
    RepositoryAnalysis,
    RepositoryStructure,
    RiskLevel,
    RobotStructure,
    SupportLevel,
    SyncMode,
    Test,
    TestCategory,
)
from framework.sync.robot_analysis import (
    analyze_robot_file,
    extract_robot_tests,
    merge_robot_structures,
)
from framework.sync.scaffold import generate_migration_worksheet
from framework.sync.sources import GitRepositorySource, LocalDirectorySource, ZipArchiveSource
from framework.sync.test_inventory import build_inventory, extract_tests, format_inventory

__all__ = [
    "DEFAULT_ADAPTERS",
    "AnalysisDiff",
    "AutomationInventory",
    "CapabilityCatalog",
    "CapabilityCategory",
    "CompatibilityReport",
    "CrossLanguageMapping",
    "CypressAdapter",
    "DetectedFramework",
    "ExecutionModel",
    "ExistingCapability",
    "Finding",
    "FrameworkAdapter",
    "GitRepositorySource",
    "JUnitAdapter",
    "LocalDirectorySource",
    "MappingRecommendation",
    "MappingStatus",
    "MigrationCandidate",
    "MigrationScope",
    "NUnitAdapter",
    "PlaywrightAdapter",
    "PytestAdapter",
    "RepositoryAnalysis",
    "RepositoryAnalyzer",
    "RepositoryStructure",
    "RiskLevel",
    "RobotBrowserLibraryAdapter",
    "RobotFrameworkAdapter",
    "RobotRequestsLibraryAdapter",
    "RobotSeleniumLibraryAdapter",
    "RobotStructure",
    "SeleniumAdapter",
    "SupportLevel",
    "SyncMode",
    "Test",
    "TestCategory",
    "TestNGAdapter",
    "WebdriverIOAdapter",
    "XUnitAdapter",
    "ZipArchiveSource",
    "analyze_robot_file",
    "build_capability_catalog",
    "build_inventory",
    "compute_compatibility_report",
    "detect_execution_model",
    "detect_reporting_tools",
    "diff_analyses",
    "extract_robot_tests",
    "extract_tests",
    "format_inventory",
    "generate_migration_worksheet",
    "lookup_cross_language_mappings",
    "merge_robot_structures",
    "recommend_mappings",
    "select_migration_candidates",
]
