from __future__ import annotations

import pytest

from framework.discovery import (
    DiscoveredColumn,
    DiscoveredElement,
    DiscoveredLocator,
    DiscoveredPage,
    DiscoveredTable,
    DiscoveryReport,
    DomainModelGenerator,
    PageObjectGenerator,
    write_generated_file,
)

pytestmark = pytest.mark.discovery


def _page() -> DiscoveredPage:
    return DiscoveredPage(
        url="https://example.test/login",
        title="Login",
        elements=[
            DiscoveredElement(
                tag="button",
                element_type="button",
                text="Sign In",
                locator=DiscoveredLocator(strategy="test_id", value="sign-in-btn"),
            ),
            DiscoveredElement(
                tag="input",
                element_type="input",
                locator=DiscoveredLocator(strategy="css", value="#username"),
            ),
        ],
    )


def _table() -> DiscoveredTable:
    return DiscoveredTable(
        name="tenants",
        columns=[
            DiscoveredColumn(name="tenant_id", type="VARCHAR", nullable=False, primary_key=True),
            DiscoveredColumn(name="active", type="BOOLEAN", nullable=True),
        ],
    )


class TestPageObjectGenerator:
    def test_generates_a_basepage_subclass_with_locator_constants(self) -> None:
        code = PageObjectGenerator.generate(_page(), class_name="LoginPageDiscovered")

        assert "class LoginPageDiscovered(BasePage):" in code
        assert "from framework.pages.base_page import BasePage" in code
        assert "'sign-in-btn'" in code
        assert "'#username'" in code

    def test_input_elements_get_a_review_required_stub(self) -> None:
        code = PageObjectGenerator.generate(_page(), class_name="LoginPageDiscovered")
        assert "NotImplementedError" in code

    def test_header_flags_the_file_as_generated(self) -> None:
        code = PageObjectGenerator.generate(_page(), class_name="LoginPageDiscovered")
        assert "GENERATED BY THE APPLICATION DISCOVERY ENGINE" in code

    def test_generated_code_is_syntactically_valid_python(self) -> None:
        code = PageObjectGenerator.generate(_page(), class_name="LoginPageDiscovered")
        compile(code, "<generated>", "exec")


class TestDomainModelGenerator:
    def test_generates_a_frozen_dataclass(self) -> None:
        code = DomainModelGenerator.generate(_table(), class_name="Tenant")

        assert "@dataclass(frozen=True, slots=True)" in code
        assert "class Tenant:" in code
        assert "tenant_id: str" in code
        assert "active: bool | None" in code

    def test_generated_code_is_syntactically_valid_python(self) -> None:
        code = DomainModelGenerator.generate(_table(), class_name="Tenant")
        compile(code, "<generated>", "exec")


def test_write_generated_file_creates_directory_and_writes_content(tmp_path) -> None:
    target = write_generated_file("print('hi')", tmp_path / "generated", "sample.py")

    assert target.exists()
    assert target.read_text(encoding="utf-8") == "print('hi')"


def test_discovery_report_round_trips_through_json(tmp_path) -> None:
    report = DiscoveryReport(source="https://example.test", pages=[_page()], tables=[_table()])
    path = tmp_path / "report.json"

    report.save(path)
    loaded = DiscoveryReport.load(path)

    assert loaded.source == "https://example.test"
    assert len(loaded.pages) == 1
    assert loaded.pages[0].url == "https://example.test/login"
    assert loaded.tables[0].name == "tenants"
